stages:
  - test
  - build
  - deploy

book:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-book.sh

generous:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-generous.sh

test:linux:
  stage: test
  tags:
    - linux
  script:
    - scripts/ci-test.sh

test:macos:
  stage: test
  tags:
    - darwin
  script:
    - scripts/ci-test.sh

test:windows:
  stage: test
  tags:
    - windows
  script:
    - scripts/ci-test.sh

build:linux:amd64:
  stage: build
  tags:
    - docker-capsule-64
  script:
    - npm ci --no-audit
    - node release/build.js --os linux --arch x86_64
    - scripts/ci-package.sh
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:darwin:amd64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os darwin --arch x86_64
    - scripts/ci-package.sh
  tags:
    - darwin
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:windows:386:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch i686
    - scripts/ci-package.sh
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:windows:amd64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch x86_64
    - scripts/ci-package.sh
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - broth

deploy-itchio:
  stage: deploy
  tags:
    - linux
  script:
    - scripts/ci-deploy-itchio.sh
