stages:
  - test
  - build
  - deploy

book:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-book.sh

generous:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-generous.sh

test:linux:
  stage: test
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/test.js

test:macos:
  stage: test
  tags:
    - darwin
  script:
    - scripts/ci-test.sh

test:windows:
  stage: test
  tags:
    - windows
  script:
    - scripts/ci-test.sh

build:linux:x86_64:
  stage: build
  tags:
    - docker-capsule-64
  script:
    - npm ci --no-audit
    - node release/build.js --os linux --arch x86_64
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:darwin:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os darwin --arch x86_64
  tags:
    - darwin
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:windows:i686:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch i686
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:windows:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch x86_64
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

deploy-itchio:
  stage: deploy
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/deploy.js
