
stages:
  - test
  - build
  - deploy

book:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-book.sh

generous:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-generous.sh

test:linux:
  stage: test
  tags:
    - linux
  script:
    - scripts/ci-test.sh

test:macos:
  stage: test
  tags:
    - darwin
  script:
    - scripts/ci-test.sh

test:windows:
  stage: test
  tags:
    - windows
  script:
    - scripts/ci-test.sh

build:linux:386:
  stage: build
  tags:
    - docker-capsule-32
  script:
    - export CI_OS=linux
    - export CI_ARCH=386
    - scripts/ci-build.sh
    - scripts/ci-package.sh
  artifacts:
    expire_in: 1 week
    paths:
      - ibrew
      - broth

build:linux:amd64:
  stage: build
  tags:
    - docker-capsule-64
  script:
    - export CI_OS=linux
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
    - scripts/ci-package.sh
  artifacts:
    expire_in: 1 week
    paths:
      - ibrew
      - broth

build:darwin:amd64:
  stage: build
  script:
    - export CI_OS=darwin
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
    - scripts/ci-package.sh
  tags:
    - darwin
  artifacts:
    expire_in: 1 week
    paths:
      - ibrew
      - broth

build:windows:386:
  stage: build
  script:
    - export CI_OS=windows
    - export CI_ARCH=386
    - scripts/ci-build.sh
    - scripts/ci-package.sh
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - ibrew
      - broth

build:windows:amd64:
  stage: build
  script:
    - export CI_OS=windows
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
    - scripts/ci-package.sh
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - ibrew
      - broth

deploy-ibrew:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-deploy-ibrew.sh

deploy-itchio:
  stage: deploy
  tags:
    - linux
  script:
    - scripts/ci-deploy-itchio.sh
